name: Makefile CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make install 

    - name: lint with pylint
      run: make lint
      
    - name: test with pytest
      run: make test
    
    - name: format with black
      run: make format
